/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginOtpRouteImport } from './routes/login/otp'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedWebhooksIndexRouteImport } from './routes/_authenticated/webhooks/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTablesIndexRouteImport } from './routes/_authenticated/tables/index'
import { Route as AuthenticatedStorageIndexRouteImport } from './routes/_authenticated/storage/index'
import { Route as AuthenticatedStorageConfigIndexRouteImport } from './routes/_authenticated/storage-config/index'
import { Route as AuthenticatedSqlEditorIndexRouteImport } from './routes/_authenticated/sql-editor/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSecuritySettingsIndexRouteImport } from './routes/_authenticated/security-settings/index'
import { Route as AuthenticatedRpcIndexRouteImport } from './routes/_authenticated/rpc/index'
import { Route as AuthenticatedRealtimeIndexRouteImport } from './routes/_authenticated/realtime/index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring/index'
import { Route as AuthenticatedKnowledgeBasesIndexRouteImport } from './routes/_authenticated/knowledge-bases/index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedFunctionsIndexRouteImport } from './routes/_authenticated/functions/index'
import { Route as AuthenticatedFeaturesIndexRouteImport } from './routes/_authenticated/features/index'
import { Route as AuthenticatedExtensionsIndexRouteImport } from './routes/_authenticated/extensions/index'
import { Route as AuthenticatedEmailSettingsIndexRouteImport } from './routes/_authenticated/email-settings/index'
import { Route as AuthenticatedDatabaseConfigIndexRouteImport } from './routes/_authenticated/database-config/index'
import { Route as AuthenticatedChatbotsIndexRouteImport } from './routes/_authenticated/chatbots/index'
import { Route as AuthenticatedAuthenticationIndexRouteImport } from './routes/_authenticated/authentication/index'
import { Route as AuthenticatedApiKeysIndexRouteImport } from './routes/_authenticated/api-keys/index'
import { Route as AuthenticatedAiProvidersIndexRouteImport } from './routes/_authenticated/ai-providers/index'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedApiRestRouteImport } from './routes/_authenticated/api/rest'
import { Route as AuthenticatedKnowledgeBasesIdIndexRouteImport } from './routes/_authenticated/knowledge-bases/$id/index'
import { Route as AuthenticatedKnowledgeBasesIdSettingsRouteImport } from './routes/_authenticated/knowledge-bases/$id/settings'
import { Route as AuthenticatedKnowledgeBasesIdSearchRouteImport } from './routes/_authenticated/knowledge-bases/$id/search'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/login/otp',
  path: '/login/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebhooksIndexRoute =
  AuthenticatedWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTablesIndexRoute =
  AuthenticatedTablesIndexRouteImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStorageIndexRoute =
  AuthenticatedStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStorageConfigIndexRoute =
  AuthenticatedStorageConfigIndexRouteImport.update({
    id: '/storage-config/',
    path: '/storage-config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSqlEditorIndexRoute =
  AuthenticatedSqlEditorIndexRouteImport.update({
    id: '/sql-editor/',
    path: '/sql-editor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecuritySettingsIndexRoute =
  AuthenticatedSecuritySettingsIndexRouteImport.update({
    id: '/security-settings/',
    path: '/security-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRpcIndexRoute = AuthenticatedRpcIndexRouteImport.update({
  id: '/rpc/',
  path: '/rpc/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRealtimeIndexRoute =
  AuthenticatedRealtimeIndexRouteImport.update({
    id: '/realtime/',
    path: '/realtime/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeBasesIndexRoute =
  AuthenticatedKnowledgeBasesIndexRouteImport.update({
    id: '/knowledge-bases/',
    path: '/knowledge-bases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunctionsIndexRoute =
  AuthenticatedFunctionsIndexRouteImport.update({
    id: '/functions/',
    path: '/functions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeaturesIndexRoute =
  AuthenticatedFeaturesIndexRouteImport.update({
    id: '/features/',
    path: '/features/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtensionsIndexRoute =
  AuthenticatedExtensionsIndexRouteImport.update({
    id: '/extensions/',
    path: '/extensions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailSettingsIndexRoute =
  AuthenticatedEmailSettingsIndexRouteImport.update({
    id: '/email-settings/',
    path: '/email-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatabaseConfigIndexRoute =
  AuthenticatedDatabaseConfigIndexRouteImport.update({
    id: '/database-config/',
    path: '/database-config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatbotsIndexRoute =
  AuthenticatedChatbotsIndexRouteImport.update({
    id: '/chatbots/',
    path: '/chatbots/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuthenticationIndexRoute =
  AuthenticatedAuthenticationIndexRouteImport.update({
    id: '/authentication/',
    path: '/authentication/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiKeysIndexRoute =
  AuthenticatedApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiProvidersIndexRoute =
  AuthenticatedAiProvidersIndexRouteImport.update({
    id: '/ai-providers/',
    path: '/ai-providers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiRestRoute = AuthenticatedApiRestRouteImport.update({
  id: '/api/rest',
  path: '/api/rest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeBasesIdIndexRoute =
  AuthenticatedKnowledgeBasesIdIndexRouteImport.update({
    id: '/knowledge-bases/$id/',
    path: '/knowledge-bases/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeBasesIdSettingsRoute =
  AuthenticatedKnowledgeBasesIdSettingsRouteImport.update({
    id: '/knowledge-bases/$id/settings',
    path: '/knowledge-bases/$id/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeBasesIdSearchRoute =
  AuthenticatedKnowledgeBasesIdSearchRouteImport.update({
    id: '/knowledge-bases/$id/search',
    path: '/knowledge-bases/$id/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/setup': typeof SetupRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/login/otp': typeof LoginOtpRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/rest': typeof AuthenticatedApiRestRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/ai-providers': typeof AuthenticatedAiProvidersIndexRoute
  '/api-keys': typeof AuthenticatedApiKeysIndexRoute
  '/authentication': typeof AuthenticatedAuthenticationIndexRoute
  '/chatbots': typeof AuthenticatedChatbotsIndexRoute
  '/database-config': typeof AuthenticatedDatabaseConfigIndexRoute
  '/email-settings': typeof AuthenticatedEmailSettingsIndexRoute
  '/extensions': typeof AuthenticatedExtensionsIndexRoute
  '/features': typeof AuthenticatedFeaturesIndexRoute
  '/functions': typeof AuthenticatedFunctionsIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/knowledge-bases': typeof AuthenticatedKnowledgeBasesIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/realtime': typeof AuthenticatedRealtimeIndexRoute
  '/rpc': typeof AuthenticatedRpcIndexRoute
  '/security-settings': typeof AuthenticatedSecuritySettingsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sql-editor': typeof AuthenticatedSqlEditorIndexRoute
  '/storage-config': typeof AuthenticatedStorageConfigIndexRoute
  '/storage': typeof AuthenticatedStorageIndexRoute
  '/tables': typeof AuthenticatedTablesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/webhooks': typeof AuthenticatedWebhooksIndexRoute
  '/knowledge-bases/$id/search': typeof AuthenticatedKnowledgeBasesIdSearchRoute
  '/knowledge-bases/$id/settings': typeof AuthenticatedKnowledgeBasesIdSettingsRoute
  '/knowledge-bases/$id': typeof AuthenticatedKnowledgeBasesIdIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/login/otp': typeof LoginOtpRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/rest': typeof AuthenticatedApiRestRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/ai-providers': typeof AuthenticatedAiProvidersIndexRoute
  '/api-keys': typeof AuthenticatedApiKeysIndexRoute
  '/authentication': typeof AuthenticatedAuthenticationIndexRoute
  '/chatbots': typeof AuthenticatedChatbotsIndexRoute
  '/database-config': typeof AuthenticatedDatabaseConfigIndexRoute
  '/email-settings': typeof AuthenticatedEmailSettingsIndexRoute
  '/extensions': typeof AuthenticatedExtensionsIndexRoute
  '/features': typeof AuthenticatedFeaturesIndexRoute
  '/functions': typeof AuthenticatedFunctionsIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/knowledge-bases': typeof AuthenticatedKnowledgeBasesIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/realtime': typeof AuthenticatedRealtimeIndexRoute
  '/rpc': typeof AuthenticatedRpcIndexRoute
  '/security-settings': typeof AuthenticatedSecuritySettingsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sql-editor': typeof AuthenticatedSqlEditorIndexRoute
  '/storage-config': typeof AuthenticatedStorageConfigIndexRoute
  '/storage': typeof AuthenticatedStorageIndexRoute
  '/tables': typeof AuthenticatedTablesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/webhooks': typeof AuthenticatedWebhooksIndexRoute
  '/knowledge-bases/$id/search': typeof AuthenticatedKnowledgeBasesIdSearchRoute
  '/knowledge-bases/$id/settings': typeof AuthenticatedKnowledgeBasesIdSettingsRoute
  '/knowledge-bases/$id': typeof AuthenticatedKnowledgeBasesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/login/otp': typeof LoginOtpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/api/rest': typeof AuthenticatedApiRestRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/ai-providers/': typeof AuthenticatedAiProvidersIndexRoute
  '/_authenticated/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/_authenticated/authentication/': typeof AuthenticatedAuthenticationIndexRoute
  '/_authenticated/chatbots/': typeof AuthenticatedChatbotsIndexRoute
  '/_authenticated/database-config/': typeof AuthenticatedDatabaseConfigIndexRoute
  '/_authenticated/email-settings/': typeof AuthenticatedEmailSettingsIndexRoute
  '/_authenticated/extensions/': typeof AuthenticatedExtensionsIndexRoute
  '/_authenticated/features/': typeof AuthenticatedFeaturesIndexRoute
  '/_authenticated/functions/': typeof AuthenticatedFunctionsIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/knowledge-bases/': typeof AuthenticatedKnowledgeBasesIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/realtime/': typeof AuthenticatedRealtimeIndexRoute
  '/_authenticated/rpc/': typeof AuthenticatedRpcIndexRoute
  '/_authenticated/security-settings/': typeof AuthenticatedSecuritySettingsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sql-editor/': typeof AuthenticatedSqlEditorIndexRoute
  '/_authenticated/storage-config/': typeof AuthenticatedStorageConfigIndexRoute
  '/_authenticated/storage/': typeof AuthenticatedStorageIndexRoute
  '/_authenticated/tables/': typeof AuthenticatedTablesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/_authenticated/knowledge-bases/$id/search': typeof AuthenticatedKnowledgeBasesIdSearchRoute
  '/_authenticated/knowledge-bases/$id/settings': typeof AuthenticatedKnowledgeBasesIdSettingsRoute
  '/_authenticated/knowledge-bases/$id/': typeof AuthenticatedKnowledgeBasesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/setup'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/login/otp'
    | '/'
    | '/login'
    | '/api/rest'
    | '/errors/$error'
    | '/settings/appearance'
    | '/ai-providers'
    | '/api-keys'
    | '/authentication'
    | '/chatbots'
    | '/database-config'
    | '/email-settings'
    | '/extensions'
    | '/features'
    | '/functions'
    | '/jobs'
    | '/knowledge-bases'
    | '/monitoring'
    | '/realtime'
    | '/rpc'
    | '/security-settings'
    | '/settings'
    | '/sql-editor'
    | '/storage-config'
    | '/storage'
    | '/tables'
    | '/users'
    | '/webhooks'
    | '/knowledge-bases/$id/search'
    | '/knowledge-bases/$id/settings'
    | '/knowledge-bases/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/login/otp'
    | '/'
    | '/login'
    | '/api/rest'
    | '/errors/$error'
    | '/settings/appearance'
    | '/ai-providers'
    | '/api-keys'
    | '/authentication'
    | '/chatbots'
    | '/database-config'
    | '/email-settings'
    | '/extensions'
    | '/features'
    | '/functions'
    | '/jobs'
    | '/knowledge-bases'
    | '/monitoring'
    | '/realtime'
    | '/rpc'
    | '/security-settings'
    | '/settings'
    | '/sql-editor'
    | '/storage-config'
    | '/storage'
    | '/tables'
    | '/users'
    | '/webhooks'
    | '/knowledge-bases/$id/search'
    | '/knowledge-bases/$id/settings'
    | '/knowledge-bases/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/setup'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/login/otp'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/api/rest'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/ai-providers/'
    | '/_authenticated/api-keys/'
    | '/_authenticated/authentication/'
    | '/_authenticated/chatbots/'
    | '/_authenticated/database-config/'
    | '/_authenticated/email-settings/'
    | '/_authenticated/extensions/'
    | '/_authenticated/features/'
    | '/_authenticated/functions/'
    | '/_authenticated/jobs/'
    | '/_authenticated/knowledge-bases/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/realtime/'
    | '/_authenticated/rpc/'
    | '/_authenticated/security-settings/'
    | '/_authenticated/settings/'
    | '/_authenticated/sql-editor/'
    | '/_authenticated/storage-config/'
    | '/_authenticated/storage/'
    | '/_authenticated/tables/'
    | '/_authenticated/users/'
    | '/_authenticated/webhooks/'
    | '/_authenticated/knowledge-bases/$id/search'
    | '/_authenticated/knowledge-bases/$id/settings'
    | '/_authenticated/knowledge-bases/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  LoginOtpRoute: typeof LoginOtpRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/login/otp': {
      id: '/login/otp'
      path: '/login/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/webhooks/': {
      id: '/_authenticated/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tables/': {
      id: '/_authenticated/tables/'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AuthenticatedTablesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage/': {
      id: '/_authenticated/storage/'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage-config/': {
      id: '/_authenticated/storage-config/'
      path: '/storage-config'
      fullPath: '/storage-config'
      preLoaderRoute: typeof AuthenticatedStorageConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sql-editor/': {
      id: '/_authenticated/sql-editor/'
      path: '/sql-editor'
      fullPath: '/sql-editor'
      preLoaderRoute: typeof AuthenticatedSqlEditorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security-settings/': {
      id: '/_authenticated/security-settings/'
      path: '/security-settings'
      fullPath: '/security-settings'
      preLoaderRoute: typeof AuthenticatedSecuritySettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rpc/': {
      id: '/_authenticated/rpc/'
      path: '/rpc'
      fullPath: '/rpc'
      preLoaderRoute: typeof AuthenticatedRpcIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/realtime/': {
      id: '/_authenticated/realtime/'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof AuthenticatedRealtimeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-bases/': {
      id: '/_authenticated/knowledge-bases/'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases'
      preLoaderRoute: typeof AuthenticatedKnowledgeBasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/functions/': {
      id: '/_authenticated/functions/'
      path: '/functions'
      fullPath: '/functions'
      preLoaderRoute: typeof AuthenticatedFunctionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/features/': {
      id: '/_authenticated/features/'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthenticatedFeaturesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extensions/': {
      id: '/_authenticated/extensions/'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof AuthenticatedExtensionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-settings/': {
      id: '/_authenticated/email-settings/'
      path: '/email-settings'
      fullPath: '/email-settings'
      preLoaderRoute: typeof AuthenticatedEmailSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database-config/': {
      id: '/_authenticated/database-config/'
      path: '/database-config'
      fullPath: '/database-config'
      preLoaderRoute: typeof AuthenticatedDatabaseConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbots/': {
      id: '/_authenticated/chatbots/'
      path: '/chatbots'
      fullPath: '/chatbots'
      preLoaderRoute: typeof AuthenticatedChatbotsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/authentication/': {
      id: '/_authenticated/authentication/'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticatedAuthenticationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys/': {
      id: '/_authenticated/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-providers/': {
      id: '/_authenticated/ai-providers/'
      path: '/ai-providers'
      fullPath: '/ai-providers'
      preLoaderRoute: typeof AuthenticatedAiProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api/rest': {
      id: '/_authenticated/api/rest'
      path: '/api/rest'
      fullPath: '/api/rest'
      preLoaderRoute: typeof AuthenticatedApiRestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-bases/$id/': {
      id: '/_authenticated/knowledge-bases/$id/'
      path: '/knowledge-bases/$id'
      fullPath: '/knowledge-bases/$id'
      preLoaderRoute: typeof AuthenticatedKnowledgeBasesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-bases/$id/settings': {
      id: '/_authenticated/knowledge-bases/$id/settings'
      path: '/knowledge-bases/$id/settings'
      fullPath: '/knowledge-bases/$id/settings'
      preLoaderRoute: typeof AuthenticatedKnowledgeBasesIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-bases/$id/search': {
      id: '/_authenticated/knowledge-bases/$id/search'
      path: '/knowledge-bases/$id/search'
      fullPath: '/knowledge-bases/$id/search'
      preLoaderRoute: typeof AuthenticatedKnowledgeBasesIdSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApiRestRoute: typeof AuthenticatedApiRestRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedAiProvidersIndexRoute: typeof AuthenticatedAiProvidersIndexRoute
  AuthenticatedApiKeysIndexRoute: typeof AuthenticatedApiKeysIndexRoute
  AuthenticatedAuthenticationIndexRoute: typeof AuthenticatedAuthenticationIndexRoute
  AuthenticatedChatbotsIndexRoute: typeof AuthenticatedChatbotsIndexRoute
  AuthenticatedDatabaseConfigIndexRoute: typeof AuthenticatedDatabaseConfigIndexRoute
  AuthenticatedEmailSettingsIndexRoute: typeof AuthenticatedEmailSettingsIndexRoute
  AuthenticatedExtensionsIndexRoute: typeof AuthenticatedExtensionsIndexRoute
  AuthenticatedFeaturesIndexRoute: typeof AuthenticatedFeaturesIndexRoute
  AuthenticatedFunctionsIndexRoute: typeof AuthenticatedFunctionsIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedKnowledgeBasesIndexRoute: typeof AuthenticatedKnowledgeBasesIndexRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
  AuthenticatedRealtimeIndexRoute: typeof AuthenticatedRealtimeIndexRoute
  AuthenticatedRpcIndexRoute: typeof AuthenticatedRpcIndexRoute
  AuthenticatedSecuritySettingsIndexRoute: typeof AuthenticatedSecuritySettingsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSqlEditorIndexRoute: typeof AuthenticatedSqlEditorIndexRoute
  AuthenticatedStorageConfigIndexRoute: typeof AuthenticatedStorageConfigIndexRoute
  AuthenticatedStorageIndexRoute: typeof AuthenticatedStorageIndexRoute
  AuthenticatedTablesIndexRoute: typeof AuthenticatedTablesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebhooksIndexRoute: typeof AuthenticatedWebhooksIndexRoute
  AuthenticatedKnowledgeBasesIdSearchRoute: typeof AuthenticatedKnowledgeBasesIdSearchRoute
  AuthenticatedKnowledgeBasesIdSettingsRoute: typeof AuthenticatedKnowledgeBasesIdSettingsRoute
  AuthenticatedKnowledgeBasesIdIndexRoute: typeof AuthenticatedKnowledgeBasesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApiRestRoute: AuthenticatedApiRestRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedAiProvidersIndexRoute: AuthenticatedAiProvidersIndexRoute,
  AuthenticatedApiKeysIndexRoute: AuthenticatedApiKeysIndexRoute,
  AuthenticatedAuthenticationIndexRoute: AuthenticatedAuthenticationIndexRoute,
  AuthenticatedChatbotsIndexRoute: AuthenticatedChatbotsIndexRoute,
  AuthenticatedDatabaseConfigIndexRoute: AuthenticatedDatabaseConfigIndexRoute,
  AuthenticatedEmailSettingsIndexRoute: AuthenticatedEmailSettingsIndexRoute,
  AuthenticatedExtensionsIndexRoute: AuthenticatedExtensionsIndexRoute,
  AuthenticatedFeaturesIndexRoute: AuthenticatedFeaturesIndexRoute,
  AuthenticatedFunctionsIndexRoute: AuthenticatedFunctionsIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedKnowledgeBasesIndexRoute: AuthenticatedKnowledgeBasesIndexRoute,
  AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  AuthenticatedRealtimeIndexRoute: AuthenticatedRealtimeIndexRoute,
  AuthenticatedRpcIndexRoute: AuthenticatedRpcIndexRoute,
  AuthenticatedSecuritySettingsIndexRoute:
    AuthenticatedSecuritySettingsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSqlEditorIndexRoute: AuthenticatedSqlEditorIndexRoute,
  AuthenticatedStorageConfigIndexRoute: AuthenticatedStorageConfigIndexRoute,
  AuthenticatedStorageIndexRoute: AuthenticatedStorageIndexRoute,
  AuthenticatedTablesIndexRoute: AuthenticatedTablesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebhooksIndexRoute: AuthenticatedWebhooksIndexRoute,
  AuthenticatedKnowledgeBasesIdSearchRoute:
    AuthenticatedKnowledgeBasesIdSearchRoute,
  AuthenticatedKnowledgeBasesIdSettingsRoute:
    AuthenticatedKnowledgeBasesIdSettingsRoute,
  AuthenticatedKnowledgeBasesIdIndexRoute:
    AuthenticatedKnowledgeBasesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SetupRoute: SetupRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  LoginOtpRoute: LoginOtpRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
