run:
  timeout: 5m
  tests: true
  skip-dirs:
    - internal/adminui

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
  disable-all: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude typecheck errors (these are compilation errors that should be caught by go build)
    - linters:
        - typecheck
      text: ".*"
