version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt

linters:
  default: standard
  enable:
    - gosec
    - bodyclose
    - noctx
  exclusions:
    paths:
      - "internal/adminui"
      - "**/*_test.go"
    rules:
      - linters:
          - typecheck
        text: ".*"
      - linters:
          - gosec
        text: "G115:"
      - path: 'internal/runtime/runtime\.go'
        linters:
          - gosec
        text: "G204:"
      - path: 'internal/functions/bundler\.go'
        linters:
          - gosec
        text: "G204:"
      - path: 'internal/storage/local\.go'
        linters:
          - gosec
        text: "G(304|401|501|306|301):"
      - path: 'internal/email/smtp\.go'
        linters:
          - gosec
        text: "G(101|402):"
      - path: 'internal/email/templates\.go'
        linters:
          - gosec
        text: "G304:"
      - path: 'internal/functions/loader\.go'
        linters:
          - gosec
        text: "G(304|306|301):"
      - path: 'internal/functions/bundler\.go'
        linters:
          - gosec
        text: "G(304|306|301):"
      - path: 'internal/jobs/loader\.go'
        linters:
          - gosec
        text: "G304:"
      - path: 'internal/rpc/loader\.go'
        linters:
          - gosec
        text: "G304:"
      - path: 'internal/ai/loader\.go'
        linters:
          - gosec
        text: "G304:"
      - path: 'internal/database/connection\.go'
        linters:
          - gosec
        text: "G304:"
      - path: '_test\.go'
        linters:
          - gosec
        text: "G(101|104|306|301|304|404):"
      - path: '_test\.go'
        linters:
          - errcheck
      - path: "test/"
        linters:
          - errcheck
          - bodyclose
          - noctx
          - gosec
          - staticcheck
      - path: 'internal/webhook/webhook\.go'
        linters:
          - unused
      - path: 'internal/functions/validation_test\.go'
        linters:
          - staticcheck
        text: "SA1019:"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
