version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt

linters:
  default: standard
  enable:
    - gosec
    - bodyclose
    - noctx
  exclusions:
    paths:
      - ".*internal/adminui.*"
    rules:
      - linters:
          - typecheck
        text: ".*"
      - linters:
          - gosec
        text: "G115:"
      - path: "internal/functions/runtime\\.go"
        linters:
          - gosec
        text: "G204:"
      - path: "internal/storage/local\\.go"
        linters:
          - gosec
        text: "(G401|G501|G306):"
      - path: "internal/email/smtp\\.go"
        linters:
          - gosec
        text: "(G101|G402):"
      - path: "_test\\.go"
        linters:
          - gosec
        text: "G404:"
      - path: "test/"
        linters:
          - errcheck
          - bodyclose
          - noctx
      - path: "internal/webhook/webhook\\.go"
        linters:
          - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
