{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fluxbase.fullname" . }}
  namespace: {{ default (include "fluxbase.namespace" .) .Values.metrics.serviceMonitor.namespace }}
  labels: {{- include "fluxbase.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.metrics.serviceMonitor.selector }}
  selector: {{- toYaml .Values.metrics.serviceMonitor.selector | nindent 4 }}
  {{- else }}
  selector:
    matchLabels: {{- include "fluxbase.selectorLabels" . | nindent 6 }}
  {{- end }}
  endpoints:
    - port: http
      path: /metrics
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.relabelings }}
      relabelings: {{- toYaml .Values.metrics.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      {{- end }}
{{- end }}
