-- Rollback Auth Functions

DROP FUNCTION IF EXISTS auth.disable_rls(TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS auth.enable_rls(TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS auth.is_admin() CASCADE;
DROP FUNCTION IF EXISTS auth.is_authenticated() CASCADE;
DROP FUNCTION IF EXISTS auth.current_user_role() CASCADE;
DROP FUNCTION IF EXISTS auth.role() CASCADE;
DROP FUNCTION IF EXISTS auth.jwt() CASCADE;
DROP FUNCTION IF EXISTS auth.uid() CASCADE;
DROP FUNCTION IF EXISTS auth.current_user_id() CASCADE;
