#!/bin/bash
# Fluxbase Secrets Generator
# Generates all required secrets and outputs to .env or Kubernetes Secret manifest

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Banner
echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              Fluxbase Secrets Generator                      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check dependencies
if ! command -v openssl &> /dev/null; then
    echo -e "${RED}Error: openssl is required but not installed${NC}"
    exit 1
fi

# Prompt for output format
echo -e "${BLUE}Select output format:${NC}"
echo ""
echo "1) Docker Compose (.env file)"
echo "   For use with docker-compose.minimal.yaml"
echo ""
echo "2) Kubernetes Secret (fluxbase-secrets.yaml)"
echo "   For use with Helm charts or kubectl apply"
echo ""
read -p "Enter choice [1-2]: " OUTPUT_FORMAT

case $OUTPUT_FORMAT in
    1)
        OUTPUT_TYPE="env"
        OUTPUT_FILE="$SCRIPT_DIR/.env"
        ;;
    2)
        OUTPUT_TYPE="k8s"
        OUTPUT_FILE="$SCRIPT_DIR/fluxbase-secrets.yaml"
        ;;
    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

# Check if output file exists
if [ -f "$OUTPUT_FILE" ]; then
    echo ""
    echo -e "${YELLOW}Warning: $OUTPUT_FILE already exists${NC}"
    read -p "Overwrite? [y/N]: " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo -e "${RED}Aborted.${NC}"
        exit 0
    fi
fi

# Generate secrets
echo ""
echo -e "${BLUE}Generating secrets...${NC}"

JWT_SECRET=$(openssl rand -base64 32 | tr -d '\n')
ENCRYPTION_KEY=$(openssl rand -base64 32 | head -c 32)
SETUP_TOKEN=$(openssl rand -base64 32 | tr -d '\n')
POSTGRES_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')

echo -e "${GREEN}✓ JWT Secret generated${NC}"
echo -e "${GREEN}✓ Encryption Key generated (32 chars)${NC}"
echo -e "${GREEN}✓ Setup Token generated${NC}"
echo -e "${GREEN}✓ PostgreSQL Password generated${NC}"

if [ "$OUTPUT_TYPE" = "env" ]; then
    # Generate .env file
    cat > "$OUTPUT_FILE" << EOF
# Fluxbase Secrets
# Generated by generate-keys.sh on $(date)
# For use with docker-compose.minimal.yaml

# Database
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Authentication - JWT signing secret
FLUXBASE_AUTH_JWT_SECRET=$JWT_SECRET

# Encryption - For secrets, OAuth tokens, client keys at rest
# Must be exactly 32 characters for AES-256-GCM
FLUXBASE_ENCRYPTION_KEY=$ENCRYPTION_KEY

# Admin Dashboard - Required to access /admin/setup
FLUXBASE_SECURITY_SETUP_TOKEN=$SETUP_TOKEN
EOF

    echo ""
    echo -e "${GREEN}✓ Created $OUTPUT_FILE${NC}"
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}                         Next Steps${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${YELLOW}Save your Setup Token (needed for admin dashboard):${NC}"
    echo -e "${GREEN}$SETUP_TOKEN${NC}"
    echo ""
    echo -e "${BLUE}Start Fluxbase:${NC}"
    echo "  cd $SCRIPT_DIR"
    echo "  docker compose -f docker-compose.minimal.yaml up -d"
    echo ""
    echo -e "${BLUE}Then open:${NC}"
    echo "  http://localhost:8080/admin/setup"
    echo ""

else
    # Generate Kubernetes Secret manifest
    # Base64 encode the values
    JWT_SECRET_B64=$(echo -n "$JWT_SECRET" | base64)
    ENCRYPTION_KEY_B64=$(echo -n "$ENCRYPTION_KEY" | base64)
    SETUP_TOKEN_B64=$(echo -n "$SETUP_TOKEN" | base64)
    POSTGRES_PASSWORD_B64=$(echo -n "$POSTGRES_PASSWORD" | base64)

    cat > "$OUTPUT_FILE" << EOF
# Fluxbase Kubernetes Secrets
# Generated by generate-keys.sh on $(date)
# Apply with: kubectl apply -f fluxbase-secrets.yaml -n <namespace>
#
# IMPORTANT: This file contains sensitive data!
# - Do NOT commit to version control
# - Consider using sealed-secrets, external-secrets, or a secrets manager

apiVersion: v1
kind: Secret
metadata:
  name: fluxbase-secrets
  labels:
    app.kubernetes.io/name: fluxbase
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # PostgreSQL password
  postgres-password: $POSTGRES_PASSWORD_B64

  # JWT signing secret for authentication tokens
  jwt-secret: $JWT_SECRET_B64

  # Encryption key for secrets at rest (exactly 32 chars)
  encryption-key: $ENCRYPTION_KEY_B64

  # Admin dashboard setup token
  setup-token: $SETUP_TOKEN_B64
---
# Optional: PostgreSQL secret for use with Bitnami PostgreSQL chart
# Uncomment if using postgresql.auth.existingSecret in values.yaml
# apiVersion: v1
# kind: Secret
# metadata:
#   name: fluxbase-postgresql
#   labels:
#     app.kubernetes.io/name: postgresql
# type: Opaque
# data:
#   postgres-password: $POSTGRES_PASSWORD_B64
#   password: $POSTGRES_PASSWORD_B64
EOF

    echo ""
    echo -e "${GREEN}✓ Created $OUTPUT_FILE${NC}"
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}                         Next Steps${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${YELLOW}Save your Setup Token (needed for admin dashboard):${NC}"
    echo -e "${GREEN}$SETUP_TOKEN${NC}"
    echo ""
    echo -e "${BLUE}Apply the secret:${NC}"
    echo "  kubectl apply -f $OUTPUT_FILE -n fluxbase"
    echo ""
    echo -e "${BLUE}Reference in Helm values.yaml:${NC}"
    cat << 'YAML'
fluxbase:
  existingSecret: fluxbase-secrets
  existingSecretKeys:
    jwtSecret: jwt-secret
    encryptionKey: encryption-key
    setupToken: setup-token

postgresql:
  auth:
    existingSecret: fluxbase-secrets
    secretKeys:
      adminPasswordKey: postgres-password
YAML
    echo ""
    echo -e "${YELLOW}⚠️  Security Reminder:${NC}"
    echo -e "${YELLOW}   Do NOT commit fluxbase-secrets.yaml to version control!${NC}"
    echo -e "${YELLOW}   Add it to .gitignore or use a secrets manager.${NC}"
    echo ""
fi

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Secrets generation complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
