#!/bin/bash
# Migration script to copy and convert Docusaurus content to Starlight

set -e

SOURCE_DIR="/workspace/docs/docs"
TARGET_DIR="/workspace/docs-new/src/content/docs"

echo "Migrating content from $SOURCE_DIR to $TARGET_DIR..."

# Create target directory
mkdir -p "$TARGET_DIR"

# Copy all markdown files
cp -r "$SOURCE_DIR"/* "$TARGET_DIR/"

# Remove auto-generated API docs (will be regenerated by starlight-typedoc)
rm -rf "$TARGET_DIR/api/sdk" "$TARGET_DIR/api/sdk-react" 2>/dev/null || true

# Create api directory for HTTP API docs
mkdir -p "$TARGET_DIR/api/http"

echo "Content copied successfully!"
echo ""
echo "Files to process:"
find "$TARGET_DIR" -name "*.md" | wc -l
