#!/bin/bash
# Fluxbase Quick Start
# Generates required secrets and optionally starts Fluxbase

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/deploy/.env"

# Banner
echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              Fluxbase Quick Start                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check dependencies
check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}Error: $1 is required but not installed${NC}"
        exit 1
    fi
}

check_command openssl
check_command docker

# Check for docker compose (v2) or docker-compose (v1)
if docker compose version &> /dev/null; then
    DOCKER_COMPOSE="docker compose"
elif command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE="docker-compose"
else
    echo -e "${RED}Error: docker compose is required but not installed${NC}"
    exit 1
fi

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Warning: $ENV_FILE already exists${NC}"
    read -p "Overwrite? [y/N]: " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo -e "${BLUE}Keeping existing .env file${NC}"
        echo ""
    else
        rm "$ENV_FILE"
    fi
fi

# Generate secrets if .env doesn't exist
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${BLUE}Generating secrets...${NC}"

    # Generate secrets
    JWT_SECRET=$(openssl rand -base64 32 | tr -d '\n')
    ENCRYPTION_KEY=$(openssl rand -base64 32 | head -c 32)
    SETUP_TOKEN=$(openssl rand -base64 32 | tr -d '\n')
    POSTGRES_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')

    # Write .env file
    cat > "$ENV_FILE" << EOF
# Fluxbase Quick Start Configuration
# Generated by quick-start.sh on $(date)

# Database
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Authentication
FLUXBASE_AUTH_JWT_SECRET=$JWT_SECRET

# Encryption (for secrets, OAuth tokens, client keys)
FLUXBASE_ENCRYPTION_KEY=$ENCRYPTION_KEY

# Admin Dashboard Access
FLUXBASE_SECURITY_SETUP_TOKEN=$SETUP_TOKEN
EOF

    echo -e "${GREEN}✓ Generated secrets${NC}"
    echo -e "${GREEN}✓ Created $ENV_FILE${NC}"
    echo ""
    echo -e "${YELLOW}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${YELLOW}  Use the setup token for creating the first user of the admin dashboard:${NC}"
    echo -e "${GREEN}  $SETUP_TOKEN${NC}"
    echo -e "${YELLOW}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
fi

# Ask to start
read -p "Start Fluxbase now? [y/N]: " START_NOW

if [ "$START_NOW" = "y" ] || [ "$START_NOW" = "Y" ]; then
    echo ""
    echo -e "${BLUE}Starting containers...${NC}"
    cd "$PROJECT_DIR/deploy"
    $DOCKER_COMPOSE -f docker-compose.minimal.yaml up -d

    echo ""
    echo -e "${GREEN}✓ Fluxbase is starting!${NC}"
    echo ""
    echo -e "${BLUE}  Dashboard:  ${NC}http://localhost:8080/admin"
    echo -e "${BLUE}  API:        ${NC}http://localhost:8080/api/v1"
    echo -e "${BLUE}  Health:     ${NC}http://localhost:8080/health"
    echo ""
    echo -e "${YELLOW}Note: First startup may take 30-60 seconds for migrations${NC}"
    echo -e "${YELLOW}Check logs with: docker logs -f fluxbase${NC}"
else
    echo ""
    echo -e "${BLUE}To start Fluxbase:${NC}"
    echo "  cd $PROJECT_DIR/deploy"
    echo "  $DOCKER_COMPOSE -f docker-compose.minimal.yaml up -d"
    echo ""
fi
