import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // 📚 Documentation sidebar - Getting started and core concepts
  docsSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "👋 Introduction",
    },
    {
      type: "category",
      label: "🚀 Getting Started",
      items: [
        "getting-started/installation",
        "getting-started/quick-start",
      ],
    },
    {
      type: "category",
      label: "⚙️ Configuration",
      items: [
        "reference/configuration",
      ],
    },
    {
      type: "doc",
      id: "api-cookbook",
      label: "📖 API Cookbook",
    },
    {
      type: "doc",
      id: "supabase-comparison",
      label: "🔄 Supabase Comparison",
    },
  ],

  // 📖 Guides sidebar - Feature-specific guides
  guidesSidebar: [
    {
      type: "doc",
      id: "guides/authentication",
      label: "🔐 Authentication",
    },
    {
      type: "doc",
      id: "guides/realtime",
      label: "📡 Realtime",
    },
    {
      type: "doc",
      id: "guides/storage",
      label: "📦 Storage",
    },
    {
      type: "doc",
      id: "guides/row-level-security",
      label: "🔒 Row Level Security",
    },
    {
      type: "doc",
      id: "guides/webhooks",
      label: "🪝 Webhooks",
    },
    {
      type: "doc",
      id: "guides/edge-functions",
      label: "⚡ Edge Functions",
    },
    {
      type: "doc",
      id: "guides/jobs",
      label: "⚙️ Background Jobs",
    },
    {
      type: "doc",
      id: "guides/email-services",
      label: "📧 Email Services",
    },
    {
      type: "doc",
      id: "guides/rate-limiting",
      label: "⏱️ Rate Limiting",
    },
    {
      type: "doc",
      id: "guides/monitoring-observability",
      label: "📊 Monitoring & Observability",
    },
    {
      type: "doc",
      id: "guides/logging",
      label: "📝 Logging",
    },
    {
      type: "doc",
      id: "guides/testing",
      label: "🧪 Testing",
    },
    {
      type: "category",
      label: "🔐 Security",
      items: [
        "security/overview",
        "security/csrf-protection",
        "security/security-headers",
        "security/best-practices",
      ],
    },
    {
      type: "category",
      label: "💻 TypeScript SDK",
      items: [
        "guides/typescript-sdk/index",
        "guides/typescript-sdk/getting-started",
        "guides/typescript-sdk/database",
        "guides/typescript-sdk/react-hooks",
        "sdk/admin",
        "sdk/management",
        "sdk/settings",
        "sdk/ddl",
        "sdk/oauth",
        "sdk/impersonation",
        "sdk/advanced-features",
      ],
    },
    {
      type: "category",
      label: "⚙️ Admin Dashboard",
      items: [
        "guides/admin/index",
        "guides/admin/user-impersonation",
      ],
    },
  ],

  // 🔌 API Reference sidebar - HTTP and SDK API references
  apiSidebar: [
    {
      type: "category",
      label: "💻 TypeScript SDK API",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "api/sdk",
        },
      ],
    },
    {
      type: "category",
      label: "⚛️ React SDK API",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "api/sdk-react",
        },
      ],
    },
  ],
};

export default sidebars;
