import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // 📚 Documentation sidebar - Getting started and core concepts
  docsSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "👋 Introduction",
    },
    {
      type: "category",
      label: "🚀 Getting Started",
      items: [
        "getting-started/installation",
        "getting-started/quick-start",
      ],
    },
    {
      type: "category",
      label: "⚙️ Configuration",
      items: [
        "reference/configuration",
      ],
    },
    {
      type: "doc",
      id: "api-cookbook",
      label: "📖 API Cookbook",
    },
    {
      type: "doc",
      id: "supabase-migration",
      label: "🔄 Migrate from Supabase",
    },
    {
      type: "doc",
      id: "advanced-guides",
      label: "🚀 Advanced Guides",
    },
    {
      type: "doc",
      id: "testing-guide",
      label: "🧪 Testing Guide",
    },
  ],

  // 📖 Guides sidebar - Feature-specific guides
  guidesSidebar: [
    {
      type: "doc",
      id: "guides/authentication",
      label: "🔐 Authentication",
    },
    {
      type: "doc",
      id: "guides/realtime",
      label: "📡 Realtime",
    },
    {
      type: "doc",
      id: "guides/storage",
      label: "📦 Storage",
    },
    {
      type: "category",
      label: "💻 TypeScript SDK",
      items: [
        "guides/typescript-sdk/index",
        "guides/typescript-sdk/getting-started",
        "guides/typescript-sdk/database",
        "guides/typescript-sdk/react-hooks",
      ],
    },
    {
      type: "category",
      label: "⚙️ Admin Dashboard",
      items: [
        "guides/admin/index",
        "guides/admin/user-impersonation",
      ],
    },
  ],

  // 🔌 API Reference sidebar - HTTP and SDK API references
  apiSidebar: [
    {
      type: "category",
      label: "📡 HTTP REST API",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/rest",
          label: "Tables",
        },
        {
          type: "doc",
          id: "api/authentication",
          label: "Authentication",
        },
        {
          type: "doc",
          id: "api/storage",
          label: "Storage",
        },
        {
          type: "doc",
          id: "api/realtime",
          label: "Realtime",
        },
      ],
    },
    {
      type: "category",
      label: "💻 TypeScript SDK API",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "api/sdk",
        },
      ],
    },
    {
      type: "category",
      label: "⚛️ React SDK API",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "api/sdk-react",
        },
      ],
    },
  ],
};

export default sidebars;
